export const INCREMENT = 'INCREMENT';
export const CHOOSE_CATEGORY = 'CHOOSE_CATEGORY';
export const DISABLE_BUTTONS = 'DISABLE_BUTTONS';
export const ENABLE_BUTTONS = 'ENABLE_BUTTONS';

export const SHOW_MENU = 'SHOW_MENU';
export const PLAY_MODE = 'PLAY_MODE';
export const TRAIN_MODE = 'TRAIN_MODE';
export const ACTIVE_CATEGORY = 'ACTIVE_CATEGORY';
export const START_GAME = 'START_GAME';
export const END_GAME = 'END_GAME';

export const CORRECT_INCREMENT = 'CORRECT_INCREMENT';
export const MISTAKES_INCREMENT = 'MISTAKES_INCREMENT';
export const RESET_COUNTER = 'RESET_COUNTER';
export const RESET_MISTAKE_COUNTER = 'RESET_MISTAKE_COUNTER';
export const MODE_FLAG_RESET = 'MODE_FLAG_RESET';
